apiVersion: apps/v1
kind: Deployment
metadata:
  name: refhired-deployment
  labels:
    app: refhired
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refhired
  template:
    metadata:
      labels:
        app: refhired
    spec:
      containers:
        - name: refhired-ctr
          image: #TBD
          ports:
            - containerPort: 3000
---
# Commenting stuff because I have added loadbalancer service
apiVersion: v1
kind: Service
metadata:
  name: refhired-service
spec:
  selector:
    app: refhired
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
